import { createFileRoute } from "@tanstack/react-router"
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/AppSidebar"
import { LocationsPage } from "@/components/locations/LocationsPage"
import type { LocationsData } from "@/types/entities"

export const Route = createFileRoute("/locations")({
  component: LocationsRoute,
})

// Demo data
const demoData: LocationsData = {
  kpis: {
    totalLocations: 500,
    availableLocations: 125,
    occupiedLocations: 320,
    blockedLocations: 15,
    reservedLocations: 40,
    totalCapacity: 25000,
    usedCapacity: 18750,
    averageOccupancy: 75,
  },
  locations: [
    {
      id: "loc-1",
      code: "A-01-01-01",
      sectorId: "sec-1",
      sectorName: "Sector A1",
      zoneId: "zone-1",
      zoneName: "Storage Zone A",
      warehouseId: "wh-1",
      warehouseName: "Paris North Warehouse",
      type: "rack",
      capacity: 100,
      usedCapacity: 90,
      productCount: 3,
      pickerCount: 1,
      aisle: "A",
      level: 1,
      position: "01",
      barcode: "7500012345678",
      products: [
        { id: "p1", sku: "WID-XL-001", name: "Widget XL", quantity: 50 },
        { id: "p2", sku: "GAD-PRO-002", name: "Gadget Pro", quantity: 30 },
        { id: "p3", sku: "COM-Z-003", name: "Component Z", quantity: 10 },
      ],
      status: "occupied",
      lastUpdated: "2025-01-28T10:30:00Z",
    },
    {
      id: "loc-2",
      code: "A-01-01-02",
      sectorId: "sec-1",
      sectorName: "Sector A1",
      zoneId: "zone-1",
      zoneName: "Storage Zone A",
      warehouseId: "wh-1",
      warehouseName: "Paris North Warehouse",
      type: "rack",
      capacity: 100,
      usedCapacity: 80,
      productCount: 2,
      pickerCount: 0,
      aisle: "A",
      level: 1,
      position: "02",
      products: [
        { id: "p4", sku: "PRO-A-001", name: "Product A", quantity: 50 },
        { id: "p5", sku: "PRO-B-002", name: "Product B", quantity: 30 },
      ],
      status: "occupied",
      lastUpdated: "2025-01-28T10:25:00Z",
    },
    {
      id: "loc-3",
      code: "A-01-02-01",
      sectorId: "sec-1",
      sectorName: "Sector A1",
      zoneId: "zone-1",
      zoneName: "Storage Zone A",
      warehouseId: "wh-1",
      warehouseName: "Paris North Warehouse",
      type: "rack",
      capacity: 100,
      usedCapacity: 0,
      productCount: 0,
      pickerCount: 0,
      aisle: "A",
      level: 1,
      position: "03",
      products: [],
      status: "available",
      lastUpdated: "2025-01-28T09:00:00Z",
    },
    {
      id: "loc-4",
      code: "B-01-01-01",
      sectorId: "sec-3",
      sectorName: "Sector B1",
      zoneId: "zone-2",
      zoneName: "Receiving Zone",
      warehouseId: "wh-1",
      warehouseName: "Paris North Warehouse",
      type: "floor",
      capacity: 200,
      usedCapacity: 105,
      productCount: 2,
      pickerCount: 1,
      aisle: "B",
      level: 1,
      position: "01",
      products: [
        { id: "p6", sku: "ITM-X-001", name: "Item X", quantity: 70 },
        { id: "p7", sku: "ITM-Y-002", name: "Item Y", quantity: 35 },
      ],
      status: "occupied",
      lastUpdated: "2025-01-28T11:00:00Z",
    },
    {
      id: "loc-5",
      code: "D-01-01-01",
      sectorId: "sec-5",
      sectorName: "Sector D1",
      zoneId: "zone-4",
      zoneName: "Picking Zone",
      warehouseId: "wh-1",
      warehouseName: "Paris North Warehouse",
      type: "shelf",
      capacity: 50,
      usedCapacity: 34,
      productCount: 2,
      pickerCount: 0,
      aisle: "D",
      level: 1,
      position: "01",
      products: [
        { id: "p8", sku: "SML-A-001", name: "Small Part A", quantity: 20 },
        { id: "p9", sku: "SML-B-002", name: "Small Part B", quantity: 14 },
      ],
      status: "occupied",
      lastUpdated: "2025-01-28T10:45:00Z",
    },
    {
      id: "loc-6",
      code: "E-01-01-01",
      sectorId: "sec-6",
      sectorName: "Sector E1",
      zoneId: "zone-7",
      zoneName: "Storage Zone B",
      warehouseId: "wh-2",
      warehouseName: "Lyon Warehouse",
      type: "rack",
      capacity: 100,
      usedCapacity: 80,
      productCount: 2,
      pickerCount: 1,
      aisle: "E",
      level: 1,
      position: "01",
      products: [
        { id: "p10", sku: "MED-A-001", name: "Medium Item A", quantity: 50 },
        { id: "p11", sku: "MED-B-002", name: "Medium Item B", quantity: 30 },
      ],
      status: "occupied",
      lastUpdated: "2025-01-28T09:30:00Z",
    },
    {
      id: "loc-7",
      code: "F-01-01-01",
      sectorId: "sec-7",
      sectorName: "Sector F1",
      zoneId: "zone-8",
      zoneName: "Receiving Zone",
      warehouseId: "wh-2",
      warehouseName: "Lyon Warehouse",
      type: "floor",
      capacity: 150,
      usedCapacity: 0,
      productCount: 0,
      pickerCount: 0,
      aisle: "F",
      level: 1,
      position: "01",
      products: [],
      status: "available",
      lastUpdated: "2025-01-28T08:00:00Z",
    },
    {
      id: "loc-8",
      code: "G-01-01-01",
      sectorId: "sec-8",
      sectorName: "Sector G1",
      zoneId: "zone-11",
      zoneName: "Storage Zone C",
      warehouseId: "wh-3",
      warehouseName: "Marseille Warehouse",
      type: "rack",
      capacity: 100,
      usedCapacity: 100,
      productCount: 4,
      pickerCount: 1,
      aisle: "G",
      level: 1,
      position: "01",
      products: [
        { id: "p12", sku: "BLK-1-001", name: "Bulk Product 1", quantity: 30 },
        { id: "p13", sku: "BLK-2-002", name: "Bulk Product 2", quantity: 25 },
        { id: "p14", sku: "BLK-3-003", name: "Bulk Product 3", quantity: 25 },
        { id: "p15", sku: "BLK-4-004", name: "Bulk Product 4", quantity: 20 },
      ],
      status: "full",
      lastUpdated: "2025-01-28T11:00:00Z",
    },
    {
      id: "loc-9",
      code: "I-01-01-01",
      sectorId: "sec-10",
      sectorName: "Sector I1",
      zoneId: "zone-15",
      zoneName: "Picking Zone",
      warehouseId: "wh-4",
      warehouseName: "Bordeaux Warehouse",
      type: "bin",
      capacity: 30,
      usedCapacity: 14,
      productCount: 2,
      pickerCount: 0,
      aisle: "I",
      level: 1,
      position: "01",
      products: [
        { id: "p16", sku: "TNY-X-001", name: "Tiny Component X", quantity: 10 },
        { id: "p17", sku: "TNY-Y-002", name: "Tiny Component Y", quantity: 4 },
      ],
      status: "occupied",
      lastUpdated: "2025-01-28T10:30:00Z",
    },
    {
      id: "loc-10",
      code: "J-01-01-01",
      sectorId: "sec-11",
      sectorName: "Sector J1",
      zoneId: "zone-16",
      zoneName: "Storage Zone E",
      warehouseId: "wh-5",
      warehouseName: "Lille Warehouse",
      type: "rack",
      capacity: 100,
      usedCapacity: 49,
      productCount: 1,
      pickerCount: 0,
      aisle: "J",
      level: 1,
      position: "01",
      products: [
        { id: "p18", sku: "LRG-A-001", name: "Large Item A", quantity: 49 },
      ],
      status: "occupied",
      lastUpdated: "2025-01-28T09:45:00Z",
    },
  ],
}

function LocationsRoute() {
  return (
    <SidebarProvider>
      <div className="flex min-h-screen w-full">
        <AppSidebar />
        <main className="flex-1">
          <header className="sticky top-0 z-10 flex h-14 items-center gap-2 border-b bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60 px-2">
            <SidebarTrigger />
            <div className="flex-1" />
          </header>
          <div className="p-8">
            <LocationsPage data={demoData} />
          </div>
        </main>
      </div>
    </SidebarProvider>
  )
}
