import { createFileRoute } from "@tanstack/react-router"
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/AppSidebar"
import { SectorsPage } from "@/components/sectors/SectorsPage"
import type { SectorsData } from "@/types/entities"

export const Route = createFileRoute("/sectors")({
  component: SectorsRoute,
})

// Demo data
const demoData: SectorsData = {
  kpis: {
    totalSectors: 120,
    activeSectors: 108,
    totalCapacity: 75000,
    usedCapacity: 52500,
    averageOccupancy: 70,
    sectorTypes: {
      rack: 60,
      shelf: 25,
      floor: 20,
      bin: 10,
      mezzanine: 5,
    },
  },
  sectors: [
    {
      id: "sec-1",
      code: "S-PAR-01-A",
      name: "Sector A1",
      zoneId: "zone-1",
      zoneName: "Storage Zone A",
      warehouseId: "wh-1",
      warehouseName: "Paris North Warehouse",
      type: "rack",
      capacity: 2000,
      usedCapacity: 1700,
      locationCount: 30,
      pickerCount: 2,
      aisle: "A",
      level: 1,
      position: "01-10",
      status: "active",
      lastUpdated: "2025-01-28T10:30:00Z",
    },
    {
      id: "sec-2",
      code: "S-PAR-01-B",
      name: "Sector A2",
      zoneId: "zone-1",
      zoneName: "Storage Zone A",
      warehouseId: "wh-1",
      warehouseName: "Paris North Warehouse",
      type: "rack",
      capacity: 2000,
      usedCapacity: 1700,
      locationCount: 30,
      pickerCount: 2,
      aisle: "A",
      level: 2,
      position: "01-10",
      status: "active",
      lastUpdated: "2025-01-28T10:30:00Z",
    },
    {
      id: "sec-3",
      code: "S-PAR-02-A",
      name: "Sector B1",
      zoneId: "zone-2",
      zoneName: "Receiving Zone",
      warehouseId: "wh-1",
      warehouseName: "Paris North Warehouse",
      type: "floor",
      capacity: 1500,
      usedCapacity: 1050,
      locationCount: 15,
      pickerCount: 1,
      aisle: "B",
      level: 1,
      position: "01-05",
      status: "active",
      lastUpdated: "2025-01-28T09:15:00Z",
    },
    {
      id: "sec-4",
      code: "S-PAR-03-A",
      name: "Sector C1",
      zoneId: "zone-3",
      zoneName: "Shipping Zone",
      warehouseId: "wh-1",
      warehouseName: "Paris North Warehouse",
      type: "floor",
      capacity: 1500,
      usedCapacity: 1200,
      locationCount: 15,
      pickerCount: 1,
      aisle: "C",
      level: 1,
      position: "01-05",
      status: "active",
      lastUpdated: "2025-01-28T11:00:00Z",
    },
    {
      id: "sec-5",
      code: "S-PAR-04-A",
      name: "Sector D1",
      zoneId: "zone-4",
      zoneName: "Picking Zone",
      warehouseId: "wh-1",
      warehouseName: "Paris North Warehouse",
      type: "shelf",
      capacity: 800,
      usedCapacity: 680,
      locationCount: 20,
      pickerCount: 1,
      aisle: "D",
      level: 1,
      position: "01-08",
      status: "active",
      lastUpdated: "2025-01-28T10:45:00Z",
    },
    {
      id: "sec-6",
      code: "S-LYO-01-A",
      name: "Sector E1",
      zoneId: "zone-7",
      zoneName: "Storage Zone B",
      warehouseId: "wh-2",
      warehouseName: "Lyon Warehouse",
      type: "rack",
      capacity: 2000,
      usedCapacity: 1600,
      locationCount: 30,
      pickerCount: 1,
      aisle: "E",
      level: 1,
      position: "01-10",
      status: "active",
      lastUpdated: "2025-01-28T09:00:00Z",
    },
    {
      id: "sec-7",
      code: "S-LYO-02-A",
      name: "Sector F1",
      zoneId: "zone-8",
      zoneName: "Receiving Zone",
      warehouseId: "wh-2",
      warehouseName: "Lyon Warehouse",
      type: "floor",
      capacity: 1250,
      usedCapacity: 875,
      locationCount: 12,
      pickerCount: 1,
      aisle: "F",
      level: 1,
      position: "01-04",
      status: "active",
      lastUpdated: "2025-01-28T08:00:00Z",
    },
    {
      id: "sec-8",
      code: "S-MAR-01-A",
      name: "Sector G1",
      zoneId: "zone-11",
      zoneName: "Storage Zone C",
      warehouseId: "wh-3",
      warehouseName: "Marseille Warehouse",
      type: "rack",
      capacity: 2000,
      usedCapacity: 1800,
      locationCount: 30,
      pickerCount: 2,
      aisle: "G",
      level: 1,
      position: "01-10",
      status: "full",
      lastUpdated: "2025-01-28T11:00:00Z",
    },
    {
      id: "sec-9",
      code: "S-BOR-01-A",
      name: "Sector H1",
      zoneId: "zone-14",
      zoneName: "Storage Zone D",
      warehouseId: "wh-4",
      warehouseName: "Bordeaux Warehouse",
      type: "mezzanine",
      capacity: 1800,
      usedCapacity: 1260,
      locationCount: 25,
      pickerCount: 1,
      aisle: "H",
      level: 2,
      position: "01-08",
      status: "active",
      lastUpdated: "2025-01-28T09:00:00Z",
    },
    {
      id: "sec-10",
      code: "S-BOR-02-A",
      name: "Sector I1",
      zoneId: "zone-15",
      zoneName: "Picking Zone",
      warehouseId: "wh-4",
      warehouseName: "Bordeaux Warehouse",
      type: "bin",
      capacity: 600,
      usedCapacity: 420,
      locationCount: 15,
      pickerCount: 1,
      aisle: "I",
      level: 1,
      position: "01-06",
      status: "active",
      lastUpdated: "2025-01-28T10:30:00Z",
    },
    {
      id: "sec-11",
      code: "S-LIL-01-A",
      name: "Sector J1",
      zoneId: "zone-16",
      zoneName: "Storage Zone E",
      warehouseId: "wh-5",
      warehouseName: "Lille Warehouse",
      type: "rack",
      capacity: 1750,
      usedCapacity: 1225,
      locationCount: 25,
      pickerCount: 1,
      aisle: "J",
      level: 1,
      position: "01-09",
      status: "active",
      lastUpdated: "2025-01-28T09:30:00Z",
    },
    {
      id: "sec-12",
      code: "S-STR-01-A",
      name: "Sector K1",
      zoneId: "zone-18",
      zoneName: "Storage Zone F",
      warehouseId: "wh-6",
      warehouseName: "Strasbourg Warehouse",
      type: "rack",
      capacity: 2000,
      usedCapacity: 800,
      locationCount: 28,
      pickerCount: 0,
      aisle: "K",
      level: 1,
      position: "01-10",
      status: "inactive",
      lastUpdated: "2025-01-28T08:00:00Z",
    },
  ],
}

function SectorsRoute() {
  return (
    <SidebarProvider>
      <div className="flex min-h-screen w-full">
        <AppSidebar />
        <main className="flex-1">
          <header className="sticky top-0 z-10 flex h-14 items-center gap-2 border-b bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60 px-2">
            <SidebarTrigger />
            <div className="flex-1" />
          </header>
          <div className="p-8">
            <SectorsPage data={demoData} />
          </div>
        </main>
      </div>
    </SidebarProvider>
  )
}
