import { createFileRoute } from "@tanstack/react-router"
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/AppSidebar"
import { ZonesPage } from "@/components/zones/ZonesPage"
import type { ZonesData } from "@/types/entities"

export const Route = createFileRoute("/zones")({
  component: ZonesRoute,
})

// Demo data
const demoData: ZonesData = {
  kpis: {
    totalZones: 40,
    activeZones: 36,
    totalSurface: 42000,
    totalCapacity: 125000,
    usedCapacity: 93750,
    averageOccupancy: 75,
    zoneTypes: {
      storage: 15,
      receiving: 5,
      shipping: 5,
      picking: 8,
      packing: 4,
      cold_storage: 2,
      hazardous: 1,
    },
  },
  zones: [
    {
      id: "zone-1",
      code: "Z-PAR-01",
      name: "Zone Storage A",
      warehouseId: "wh-1",
      warehouseName: "Paris North Warehouse",
      type: "storage",
      surface: 2500,
      capacity: 8000,
      usedCapacity: 6800,
      sectorCount: 4,
      locationCount: 120,
      pickerCount: 2,
      status: "active",
      lastUpdated: "2025-01-28T10:30:00Z",
    },
    {
      id: "zone-2",
      code: "Z-PAR-02",
      name: "Receiving Zone",
      warehouseId: "wh-1",
      warehouseName: "Paris North Warehouse",
      type: "receiving",
      surface: 1500,
      capacity: 3000,
      usedCapacity: 2100,
      sectorCount: 2,
      locationCount: 45,
      pickerCount: 1,
      status: "active",
      lastUpdated: "2025-01-28T09:15:00Z",
    },
    {
      id: "zone-3",
      code: "Z-PAR-03",
      name: "Shipping Zone",
      warehouseId: "wh-1",
      warehouseName: "Paris North Warehouse",
      type: "shipping",
      surface: 1500,
      capacity: 3000,
      usedCapacity: 2400,
      sectorCount: 2,
      locationCount: 40,
      pickerCount: 1,
      status: "active",
      lastUpdated: "2025-01-28T11:00:00Z",
    },
    {
      id: "zone-4",
      code: "Z-PAR-04",
      name: "Picking Zone",
      warehouseId: "wh-1",
      warehouseName: "Paris North Warehouse",
      type: "picking",
      surface: 2000,
      capacity: 5000,
      usedCapacity: 4250,
      sectorCount: 3,
      locationCount: 80,
      pickerCount: 3,
      status: "active",
      lastUpdated: "2025-01-28T10:45:00Z",
    },
    {
      id: "zone-5",
      code: "Z-PAR-05",
      name: "Packing Zone",
      warehouseId: "wh-1",
      warehouseName: "Paris North Warehouse",
      type: "packing",
      surface: 800,
      capacity: 1500,
      usedCapacity: 900,
      sectorCount: 1,
      locationCount: 20,
      pickerCount: 1,
      status: "active",
      lastUpdated: "2025-01-28T08:30:00Z",
    },
    {
      id: "zone-6",
      code: "Z-PAR-06",
      name: "Cold Storage Zone",
      warehouseId: "wh-1",
      warehouseName: "Paris North Warehouse",
      type: "cold_storage",
      surface: 600,
      capacity: 1500,
      usedCapacity: 1350,
      sectorCount: 1,
      locationCount: 25,
      pickerCount: 0,
      temperatureMin: -18,
      temperatureMax: -15,
      status: "active",
      lastUpdated: "2025-01-28T07:00:00Z",
    },
    {
      id: "zone-7",
      code: "Z-LYO-01",
      name: "Zone Storage B",
      warehouseId: "wh-2",
      warehouseName: "Lyon Warehouse",
      type: "storage",
      surface: 2000,
      capacity: 6000,
      usedCapacity: 4800,
      sectorCount: 3,
      locationCount: 90,
      pickerCount: 1,
      status: "active",
      lastUpdated: "2025-01-28T09:00:00Z",
    },
    {
      id: "zone-8",
      code: "Z-LYO-02",
      name: "Receiving Zone",
      warehouseId: "wh-2",
      warehouseName: "Lyon Warehouse",
      type: "receiving",
      surface: 1200,
      capacity: 2500,
      usedCapacity: 1750,
      sectorCount: 2,
      locationCount: 35,
      pickerCount: 1,
      status: "active",
      lastUpdated: "2025-01-28T08:00:00Z",
    },
    {
      id: "zone-9",
      code: "Z-LYO-03",
      name: "Shipping Zone",
      warehouseId: "wh-2",
      warehouseName: "Lyon Warehouse",
      type: "shipping",
      surface: 1200,
      capacity: 2500,
      usedCapacity: 2000,
      sectorCount: 2,
      locationCount: 32,
      pickerCount: 1,
      status: "active",
      lastUpdated: "2025-01-28T10:00:00Z",
    },
    {
      id: "zone-10",
      code: "Z-LYO-04",
      name: "Picking Zone",
      warehouseId: "wh-2",
      warehouseName: "Lyon Warehouse",
      type: "picking",
      surface: 1500,
      capacity: 4000,
      usedCapacity: 3200,
      sectorCount: 2,
      locationCount: 60,
      pickerCount: 2,
      status: "active",
      lastUpdated: "2025-01-28T09:30:00Z",
    },
    {
      id: "zone-11",
      code: "Z-MAR-01",
      name: "Zone Storage C",
      warehouseId: "wh-3",
      warehouseName: "Marseille Warehouse",
      type: "storage",
      surface: 3000,
      capacity: 10000,
      usedCapacity: 9000,
      sectorCount: 5,
      locationCount: 150,
      pickerCount: 2,
      status: "full",
      lastUpdated: "2025-01-28T11:00:00Z",
    },
    {
      id: "zone-12",
      code: "Z-MAR-02",
      name: "Receiving Zone",
      warehouseId: "wh-3",
      warehouseName: "Marseille Warehouse",
      type: "receiving",
      surface: 2000,
      capacity: 4000,
      usedCapacity: 3200,
      sectorCount: 3,
      locationCount: 60,
      pickerCount: 1,
      status: "active",
      lastUpdated: "2025-01-28T10:15:00Z",
    },
    {
      id: "zone-13",
      code: "Z-MAR-03",
      name: "Hazardous Materials Zone",
      warehouseId: "wh-3",
      warehouseName: "Marseille Warehouse",
      type: "hazardous",
      surface: 500,
      capacity: 800,
      usedCapacity: 320,
      sectorCount: 1,
      locationCount: 15,
      pickerCount: 0,
      status: "active",
      lastUpdated: "2025-01-28T08:00:00Z",
    },
    {
      id: "zone-14",
      code: "Z-BOR-01",
      name: "Zone Storage D",
      warehouseId: "wh-4",
      warehouseName: "Bordeaux Warehouse",
      type: "storage",
      surface: 1800,
      capacity: 5500,
      usedCapacity: 3850,
      sectorCount: 3,
      locationCount: 80,
      pickerCount: 1,
      status: "active",
      lastUpdated: "2025-01-28T09:00:00Z",
    },
    {
      id: "zone-15",
      code: "Z-BOR-02",
      name: "Picking Zone",
      warehouseId: "wh-4",
      warehouseName: "Bordeaux Warehouse",
      type: "picking",
      surface: 1200,
      capacity: 3000,
      usedCapacity: 2100,
      sectorCount: 2,
      locationCount: 45,
      pickerCount: 2,
      status: "active",
      lastUpdated: "2025-01-28T10:30:00Z",
    },
    {
      id: "zone-16",
      code: "Z-LIL-01",
      name: "Zone Storage E",
      warehouseId: "wh-5",
      warehouseName: "Lille Warehouse",
      type: "storage",
      surface: 2200,
      capacity: 7000,
      usedCapacity: 4900,
      sectorCount: 4,
      locationCount: 100,
      pickerCount: 2,
      status: "active",
      lastUpdated: "2025-01-28T09:30:00Z",
    },
    {
      id: "zone-17",
      code: "Z-LIL-02",
      name: "Cold Storage Zone",
      warehouseId: "wh-5",
      warehouseName: "Lille Warehouse",
      type: "cold_storage",
      surface: 800,
      capacity: 2000,
      usedCapacity: 1400,
      sectorCount: 2,
      locationCount: 30,
      pickerCount: 0,
      temperatureMin: 2,
      temperatureMax: 4,
      status: "active",
      lastUpdated: "2025-01-28T07:30:00Z",
    },
    {
      id: "zone-18",
      code: "Z-STR-01",
      name: "Zone Storage F",
      warehouseId: "wh-6",
      warehouseName: "Strasbourg Warehouse",
      type: "storage",
      surface: 2500,
      capacity: 8000,
      usedCapacity: 3200,
      sectorCount: 4,
      locationCount: 110,
      pickerCount: 0,
      status: "inactive",
      lastUpdated: "2025-01-28T08:00:00Z",
    },
  ],
}

function ZonesRoute() {
  return (
    <SidebarProvider>
      <div className="flex min-h-screen w-full">
        <AppSidebar />
        <main className="flex-1">
          <header className="sticky top-0 z-10 flex h-14 items-center gap-2 border-b bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60 px-2">
            <SidebarTrigger />
            <div className="flex-1" />
          </header>
          <div className="p-8">
            <ZonesPage data={demoData} />
          </div>
        </main>
      </div>
    </SidebarProvider>
  )
}
